# -*- coding: utf-8 -*-
"""yolov5_hair_custon_train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4VRQiBNtUyhYARrOWQqH_gWoU0rW4KY
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/gdrive')
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

!rm -rf /content/yolov5/data/hair_data

# Commented out IPython magic to ensure Python compatibility.

#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies

!cp -r /content/gdrive/MyDrive/yolov5_hair_detect/hair_dataset.v2i.yolov5pytorch /content/yolov5/data

!wget https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5m.pt

!python train.py --img 640 --batch 16 --epochs 500 --data /content/yolov5/data/hair_data/data.yaml --weights /content/yolov5/yolov5m.pt --cache

!python detect.py --weights /content/yolov5/runs/train/exp2/weights/best.pt --img 640 --conf 0.1 --source /content/test49.jpg

#display inference on ALL test images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")