# -*- coding: utf-8 -*-
"""custom_hair_yolov7_segment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1ZEXm9A4VElk2AlA27LQJim7hlrtknT
"""

!rm -rf /content/yolov7-segmentation

from google.colab import drive
drive.mount('/content/gdrive')
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

#!cp -r /content/gdrive/MyDrive/yolov7_hair_segment/hair_yolov7_segmentation.v3i.yolov7pytorch /content

!git clone https://github.com/RizwanMunawar/yolov7-segmentation.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov7-segmentation

!pip install -r requirements.txt

#%cd /content/yolov7-segmentation/data
!cp -r /content/hair_dataset /content/yolov7-segmentation/data

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov7-segmentation

!ls

!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-seg.pt

!ls

!python /content/yolov7-segmentation/segment/train.py --data /content/yolov7-segmentation/data/hair_dataset/data.yaml --batch 16 --weights /content/yolov7-segmentation/yolov7-seg.pt --cfg /content/yolov7-segmentation/models/segment/yolov7-seg.yaml --epochs 500 --name yolov7-seg --img 640 --hyp /content/yolov7-segmentation/data/hyps/hyp.scratch-high.yaml

!python segment/predict.py --weights "/content/yolov7-segmentation/runs/train-seg/yolov7-seg3/weights/best.pt" --source "/content/test43.jpg"

!python segment/predict.py --weights "/content/yolov7-segmentation/runs/train-seg/yolov7-seg2/weights/best.pt" --source "/content/yolov7-segmentation/crack.mp4"

!cp -r /content/yolov7-segmentation /content/gdrive/MyDrive/yolov7_hair_segment







